In [1]:
import pandas as pd
import numpy as npb

In [21]:
import seaborn as sns
from matplotlib import pyplot as plt

In [10]:
companies = pd.read_excel("dataset.xlsx",sheetname="Companies",header=0,index_col=False,keep_default_na=True)

In [11]:
companies.head()

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at
0,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,News,1750000,acquired,USA,NY,New York City,New York,1,2012-06-01 00:00:00,2012-06,2012-Q2,2012.0,2012-06-30 00:00:00,2012-06-30 00:00:00
1,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,4000000,operating,USA,CA,Los Angeles,Los Angeles,2,NaN,NaN,NaN,NaN,2010-06-04 00:00:00,2010-09-23 00:00:00
2,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Publishing,40000,operating,EST,NaN,Tallinn,Tallinn,1,2012-10-26 00:00:00,2012-10,2012-Q4,2012.0,2012-08-09 00:00:00,2012-08-09 00:00:00
3,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Electronics,1500000,operating,GBR,NaN,London,London,1,2011-04-01 00:00:00,2011-04,2011-Q2,2011.0,2011-04-01 00:00:00,2011-04-01 00:00:00
4,/organization/r-ranch-and-mine,-R- Ranch and Mine,NaN,|Tourism|Entertainment|Games|,Tourism,60000,operating,USA,TX,Dallas,Fort Worth,2,2014-01-01 00:00:00,2014-01,2014-Q1,2014.0,2014-08-17 00:00:00,2014-09-26 00:00:00

In [12]:
rounds = pd.read_excel("dataset.xlsx",sheetname="Rounds",header=0,index_col=False,keep_default_na=True)
investments = pd.read_excel("dataset.xlsx",sheetname="Investments",header=0,index_col=False,keep_default_na=True)
acquisitions = pd.read_excel("dataset.xlsx",sheetname="Acquisitions",header=0,index_col=False,keep_default_na=True)
additions = pd.read_excel("dataset.xlsx",sheetname="Additions",header=0,index_col=False,keep_default_na=True)

In [13]:
rounds.head()

,company_permalink,company_name,company_category_list,company_market,company_country_code,company_state_code,company_region,company_city,funding_round_permalink,funding_round_type,funding_round_code,funded_at,funded_month,funded_quarter,funded_year,raised_amount_usd
0,/organization/waywire,#waywire,|Entertainment|Politics|Social Media|News|,News,USA,NY,New York City,New York,/funding-round/cc409188fa2b63482bd9008f682c2efa,seed,NaN,2012-06-30 00:00:00,2012-06,2012-Q2,2012.0,1750000.0
1,/organization/tv-communications,&TV Communications,|Games|,Games,USA,CA,Los Angeles,Los Angeles,/funding-round/59a3669a64e39360c2b939300bcda162,venture,NaN,2010-09-23 00:00:00,2010-09,2010-Q3,2010.0,3000000.0
2,/organization/tv-communications,&TV Communications,|Games|,Games,USA,CA,Los Angeles,Los Angeles,/funding-round/86d22afc65107b6941e6c43c671ecbb8,venture,NaN,2010-06-04 00:00:00,2010-06,2010-Q2,2010.0,1000000.0
3,/organization/rock-your-paper,'Rock' Your Paper,|Publishing|Education|,Publishing,EST,NaN,Tallinn,Tallinn,/funding-round/f06b420775f7cb6c1541a9db526534bb,seed,NaN,2012-08-09 00:00:00,2012-08,2012-Q3,2012.0,40000.0
4,/organization/in-touch-network,(In)Touch Network,|Electronics|Guides|Coffee|Restaurants|Music|i...,Electronics,GBR,NaN,London,London,/funding-round/33c3f135f05d7b734b8d7b7c8ae82647,seed,NaN,2011-04-01 00:00:00,2011-04,2011-Q2,2011.0,1500000.0

In [14]:
investments.head()

,company_permalink,company_name,company_category_list,company_market,company_country_code,company_state_code,company_region,company_city,investor_permalink,investor_name,...,investor_region,investor_city,funding_round_permalink,funding_round_type,funding_round_code,funded_at,funded_month,funded_quarter,funded_year,raised_amount_usd
0,/organization/test-company-3,test company,NaN,NaN,ARE,NaN,Dubai,Dubai,/person/jamessss-bondddd,jamessss bondddd,...,NaN,NaN,/funding-round/c308019016ead7afb2a1d117018eb6fc,seed,NaN,1921-09-01,1921-09,1921-Q3,1921,1000.0
1,/organization/andrewburnett-com-ltd,AndrewBurnett.com Ltd,|Internet|SEO|Services|Public Relations|Social...,Internet,GBR,NaN,Edinburgh,Edinburgh,/organization/ekaf,Ekaf,...,NaN,NaN,/funding-round/14fe2864e02d0f15ddc3ec8eacdc8e1b,seed,NaN,1974-01-01,1974-01,1974-Q1,1974,NaN
2,/organization/abo-data,ABO Data,|Enterprise Software|,Enterprise Software,USA,TX,TX - Other,Italy,/person/antonio-murroni,ANTONIO MURRONI,...,NaN,NaN,/funding-round/809e211b969c3f66440fc15ffcd29385,seed,NaN,1979-01-01,1979-01,1979-Q1,1979,1000000.0
3,/organization/abo-data,ABO Data,|Enterprise Software|,Enterprise Software,USA,TX,TX - Other,Italy,/person/filippo-murroni,FILIPPO Murroni,...,NaN,NaN,/funding-round/809e211b969c3f66440fc15ffcd29385,seed,NaN,1979-01-01,1979-01,1979-Q1,1979,1000000.0
4,/organization/ikro,Ikro,NaN,NaN,BRA,NaN,BRA - Other,Canoas,/organization/crp-companhia-de-participacoes,CRP Companhia de Participações,...,NaN,NaN,/funding-round/46c353a8249170cc4b6ab89a522fefdc,venture,A,1982-06-01,1982-06,1982-Q2,1982,724000.0

In [15]:
acquisitions.head()

,company_permalink,company_name,company_category_list,company_market,company_country_code,company_state_code,company_region,company_city,acquirer_permalink,acquirer_name,...,acquirer_country_code,acquirer_state_code,acquirer_region,acquirer_city,acquired_at,acquired_month,acquired_quarter,acquired_year,price_amount,price_currency_code
0,/organization/waywire,#waywire,|Entertainment|Politics|Social Media|News|,News,USA,NY,New York City,New York,/organization/magnify,Waywire Networks,...,USA,NY,New York City,New York,2013-10-17 00:00:00,2013-10,2013-Q4,2013.0,NaN,USD
1,/organization/fluff-friends,(fluff)Friends,NaN,NaN,NaN,NaN,NaN,NaN,/organization/social-gaming-network,SGN (Social Gaming Network),...,USA,CA,Los Angeles,Beverly Hills,2008-09-16 00:00:00,2008-09,2008-Q3,2008.0,NaN,USD
2,/organization/red,(RED),|Nonprofits|,Nonprofits,USA,NY,New York City,New York,/organization/nationstar-mortgage-holdings,Nationstar Mortgage Holdings,...,USA,TX,Dallas,Lewisville,2014-05-08 00:00:00,2014-05,2014-Q2,2014.0,18000000.0,USD
3,/organization/vandaele-holdings,.,NaN,NaN,NaN,NaN,NaN,NaN,/organization/hi7e,HI7E,...,USA,FL,Palm Beaches,West Palm Beach,2011-01-01 00:00:00,2011-01,2011-Q1,2011.0,NaN,USD
4,/organization/co-internet,.CO,|Registrars|Domains|Curated Web|,Registrars,USA,FL,Miami,Miami,/organization/neustar,Neustar,...,USA,VA,"Washington, D.C.",Sterling,2014-03-20 00:00:00,2014-03,2014-Q1,2014.0,109000000.0,USD

In [16]:
additions.head()

                   content month_str quarter_str  year_str  value
0  Profiles: Organizations   2007-05     2007-Q2      2007     14
1  Profiles: Organizations   2007-06     2007-Q2      2007     96
2  Profiles: Organizations   2007-07     2007-Q3      2007    259
3  Profiles: Organizations   2007-08     2007-Q3      2007    522
4  Profiles: Organizations   2007-09     2007-Q3      2007    219

In [22]:
investments.sort_values(['company_permalink', 'funded_month'], inplace=True)

In [23]:
investments.head()

,company_permalink,company_name,company_category_list,company_market,company_country_code,company_state_code,company_region,company_city,investor_permalink,investor_name,...,investor_region,investor_city,funding_round_permalink,funding_round_type,funding_round_code,funded_at,funded_month,funded_quarter,funded_year,raised_amount_usd
21692,/organization/0-6-com,0-6.com,|Curated Web|,Curated Web,NaN,NaN,NaN,NaN,/organization/dt-capital-partners,DT Capital Partners,...,Shanghai,Shanghai,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,2008-03-19,2008-03,2008-Q1,2008,2000000.0
107638,/organization/004-technologies,004 Technologies,|Software|,Software,USA,IL,"Springfield, Illinois",Champaign,/organization/venturecapital-de,VCDE Venture Partners,...,Frankfurt,Frankfurt Am Main,/funding-round/1278dd4e6a37fa4b7d7e06c21b3c1830,venture,NaN,2014-07-24,2014-07,2014-Q3,2014,NaN
106041,/organization/01games-technology,01Games Technology,|Games|,Games,HKG,NaN,Hong Kong,Hong Kong,/organization/cyberport-hong-kong,Cyberport Hong Kong,...,Hong Kong,Hong Kong,/funding-round/7d53696f2b4f607a2f2a8cbb83d01839,seed,NaN,2014-07-01,2014-07,2014-Q3,2014,41250.0
74152,/organization/0xdata,H2O.ai,|Analytics|,Analytics,USA,CA,SF Bay Area,Mountain View,/organization/nexus-venture-partners,Nexus Venture Partners,...,SF Bay Area,Menlo Park,/funding-round/ae2a174c06517c2394aed45006322a7e,venture,NaN,2013-01-03,2013-01,2013-Q1,2013,1700000.0
107283,/organization/0xdata,H2O.ai,|Analytics|,Analytics,USA,CA,SF Bay Area,Mountain View,/organization/nexus-venture-partners,Nexus Venture Partners,...,SF Bay Area,Menlo Park,/funding-round/e1cfcbe1bdf4c70277c5f29a3482f24e,venture,A,2014-07-19,2014-07,2014-Q3,2014,8900000.0

In [27]:
# Investment round summary
grouped_investments = investments.groupby('funding_round_type')
with pd.option_context('display.max_columns', 40):
    print(grouped_investments['raised_amount_usd'].describe(include='all'))

funding_round_type
angel                count    3.998000e+03
                     mean     1.106030e+06
                     std      2.364456e+06
                     min      0.000000e+00
                     25%               NaN
                     50%               NaN
                     75%               NaN
                     max      6.359026e+07
convertible_note     count    4.460000e+02
                     mean     1.067083e+06
                     std      1.036196e+06
                     min      1.295500e+04
                     25%               NaN
                     50%               NaN
                     75%               NaN
                     max      1.000000e+07
debt_financing       count    1.462000e+03
                     mean     2.148835e+07
                     std      5.878093e+07
                     min      1.300000e+04
                     25%               NaN
                     50%               NaN
                     75%               NaN
                     max      7.500000e+08
equity_crowdfunding  count    8.000000e+01
                     mean     5.992685e+05
                     std      1.191102e+06
                     min      1.582600e+04
                     25%      7.701500e+04
                     50%      1.602305e+05
                                  ...
secondary_market     std      5.532281e+07
                     min      2.100000e+05
                     25%               NaN
                     50%               NaN
                     75%               NaN
                     max      2.000000e+08
seed                 count    2.394200e+04
                     mean     1.076982e+06
                     std      1.356766e+06
                     min      0.000000e+00
                     25%               NaN
                     50%               NaN
                     75%               NaN
                     max      1.000000e+08
undisclosed          count    1.333000e+03
                     mean     6.221430e+06
                     std      1.690600e+07
                     min      0.000000e+00
                     25%               NaN
                     50%               NaN
                     75%               NaN
                     max      2.924328e+08
venture              count    6.706400e+04
                     mean     1.502847e+07
                     std      3.022152e+07
                     min      0.000000e+00
                     25%               NaN
                     50%               NaN
                     75%               NaN
                     max      1.200000e+09
Name: raised_amount_usd, dtype: float64

C:\Users\lakshayrastogi\Anaconda3\lib\site-packages\numpy\lib\function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

In [ ]:
investments.